export { Icon } from "./icon";
export { defaultIcons } from "./default-icons";
export {
  AddColumnIcon,
  AddRowIcon,
  AlignCenterIcon,
  AltTextIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  BoldIcon,
  ClearFormattingIcon,
  DeleteColumnIcon,
  DeleteRowIcon,
  FileIcon,
  DragHandleIcon,
  FontSizeIcon,
  HeaderRowIcon,
  HighlightIcon,
  IndentIcon,
  LinkOffIcon,
  MergeCellsIcon,
  OutdentIcon,
  PrintIcon,
  TaskListIcon,
  TrashIcon,
  UploadIcon,
  BulletListIcon,
  ChevronDownIcon,
  CodeIcon,
  DividerIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  ImageIcon,
  ItalicIcon,
  LinkIcon,
  MinusIcon,
  OrderedListIcon,
  OutlineIcon,
  PageLayoutIcon,
  ParagraphIcon,
  PlusIcon,
  QuoteIcon,
  RedoIcon,
  SearchIcon,
  StrikethroughIcon,
  TableIcon,
  UnderlineIcon,
  UndoIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "./icons";

export type { IconProps } from "./icon";
export type { DocsEditorIconName } from "./default-icons";
